Promo image (#56)
* Booking history (#38)

* remove old test data

* BookingController->getBookingByUserId()

* BookingService->getBeookingsByUserId()

* BookingRepository->getBookingsByUserId()

* update imports

* delete Reservation.php (we have Booking.php instead)

* refactor Booking -> added tickets

* refactor Ticket -> removed booking

* TicketRepository->getTicketsByBookingId()

* TicketService->getTicketsByBookingId()

* moved ticket mapping to a separate function (removed code dupl)

* revert refactoring.... see desc:

We ran into this issue:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /Applications/XAMPP/xamppfiles/htdocs/dwp/src/model/services/VenueService.php on line 19

* Revert "revert refactoring.... see desc:"

This reverts commit 26d4bca32415d9616423003ca3e42cd45b7d3662.

* Refactor: Subtracting 3 years from my life expectancy, but it's worth it

* rendering booking cards

* updated python script (one booking -> one showing)

* show more button works

* show more? show less! show MORE? show LESS!

* Admin CRUD for openinghours (#40)

* Removed unnecessary imports

* file created

* overflow hidden removed

* Updated styling

* Display venues for opening hours

* Action btn for news card styling update

* Style for opening hour card

* Code display update

* Opening Hour card component created

* Displaying opening hour cards

* Unnecessary line

* Displaying the right cards based on clicks

* get openingHoursById fetch returning empty array

* Opening hours works with dataset

* getOpeningHoursById seprarated to getCyrrentById and the original

* Returning an array of data so its not an empty array

* Displaying opening hours cards

* Switched functions

* Renaming, deleting unnecessary code, convert from post to get

* No opening hours text added

* Func merge

* Base functions added for add opening hours

* Add opening hours modal created

* Edit opening hours modal and basic functions and variables added

* Delete opening hours modal, basic functions and variables added

* Add opening hour function added

* Add opening hour function added to service

* Add opening hour function added to controller

* New validations for form inputs

* isDuplicate function added

* Check if venue exists

* Further validation for duplicate opening hours in service

* Submit form for add opening hour, and renaming

* post route for add opening hours

* Set active opening hours to inactive

* Delete venue opening hour junction table form script

* Delete venue opening hour junction table mock data

* Opening hours getdb is in repository again, updated code for get opening hours and current, and footer

* Opening hour functions reworked or removed for new database structure in repository

* Opening hour functions reworked or removed for new database structure in service

* Opening hour functions reworked  for new database structure in controller

* Venue card selection removed, openingHour cards updated for new structure

* Get opening hours based on venue card route removed

* Edit and delete button for opening hours correct syntax added

* Correct syntax for passing data

* Data binding and passing correctly for delete and edit modals

* Delete function added to repo and changing execute databinding syntax

* Delete function added to service

* Delete function added to controller

* Require controllers only once for news and openingHour, delete route for openingHour

* Delete AJAX response

* Error display properly for news crud

* Renaming

* Edit function added to repo, isDuplicate function updated for editing

* Edit function added to service

* Edit function added to controller

* Edit put route for AJAX request added

* CRUD AJAX request for edit form submission

* Error general display

* Renaming for error display, and sanitizing

* Sanitizing data

* Renaming for error display

* Sanitizing data, especially errors for display

* Sort the openingHours for display

* Admin movie details (#41)

* adding movie-management to sidebar

* populating the movies page with all movies

* added eventListener for clicking on add movie

* Adjust movieCard notToShow movieDetails after click

* Added edit movie details

* adding error handling to fetching movie data

* delete echoing

* changing logic from using cards to echoing movieposter

* created movieCard Admin component

>moved the logic from movieCard to Admin component

* new movieCardAdmin with container

* added CRUD movie through architecture

> CUD in repo
> CUD in service
> CUD in controller

* fixed logic for movies

* giving adminSideBar fixed position

* fixed issue with getting Movie type instead of array

* playing with design

* created modals for the adding, editing and deleting movie

* editing movie

* delete loging

* on allMoviesPage display only released movies

* delete movie admin

* adding movie from admin panel

>created getAllActiveMovies method through the layers

* fixed adding movie

>rating does not work properly

* fixed routing and changed movie db implementation

* archive a movie

---------

Co-authored-by: Katarína Brezániová <10407558@ucn.dk>

* Select seats + Booking overview (#42)

* updated logic for displaying showings (only display showings later than now)

* show error message when user tries to select unavailable seat

* some seat selection valdiations

* more validations 😭

* changed method call on about page

* selected seats + proceed button

* BookingController -> createBooking

* BookingService -> createBooking

* BookingRepository -> createBooking

* set 15 minutes timer, create empty booking on seat select

* userId nullable for anonymus user bookings

* making sure no more than one activeBooking can be present

* ticketcontroller->createTicket (and put it to sessions activebooking)

* ticketservice->createTicket

* remove activeBooking from session on timer expiry

* ticket create related methods

* booking status is updated to 'cancelled' when timer expires

* booking is only created when proceeding to payment

* initial booking overview page

* seatController->getSeatById

* getTicketById

* added stripe logo

* booking overview v2 + redirect back after login

* booking is rolled back on timer expiration

* rollback tickets and cancel booking

* navigation guard (?)

* removed unused method

* color legend (explanation)

* Minor updates for redirect

---------

Co-authored-by: Norbert Tolnai <tolnainorbi16@gmail.com>

* Booking navigation logic (#44)

* navigation should work nicely?

* changed xhr request to JS on profile/venue dd + format document

* i had enough of this, you cant refresh the checkout page

* Stripe added to the project (#43)

* status field added to payment

* stripe latest version included manually

* Storing the stripe keys in .env and loading it

* Temp payement file

* Test route for chekcout file

* Missing line, might not be iomportant

* Temp button for form

* Stripe payment creation

* Renaming

* Successful checkout page created

* Renaming

* temp sql script

* Temp mock data update

* Temp mockdata

* rename

* rename

* Payment entity update

* addPayment function created

* Payment entity updated

* sql script update

* Test data added for payment adding

* creating webhook file

* renaming

* webhook code added

* webhook file moved

* rename to failed

* rename to failed

* Update paymentStatus function created, dbCon moved to payment service

* Update bookingStatus function added

* dbCon brought back to repo from service

* get ids of payment function added

* PaymentStatus updated test, it is working

* Update payment based on confirmed or failed moved to webhook file

* Invoice sender function added

* Invoice sending function called

* dbSetup script renamed and altered to dev and prod

* mockdata update

* db setup script deleted to use the updated one

* unused comments removed

* Update code based on new sql script

* Update for production

* Update for production

* need for logging at least

* Small changes to production

* Error logging and code update so it works

* New email

* Delete logs

* Invoice mail was sent

* Expiration added, new event for webhook fail trigger

* typo

* New log added

* userId can be null for not authenticated users

* Webhook route

* post route for booking checkout

* Archived attribute added to movie mockData, an development db script

* transaction moved to inside try cacth

* Bug fixes + more requirements (#45)

* Rename to failed from cancelled

* mockScript renamings

* profile page bookings error handling

* changing iron man poster

* add back deleted line

* hide venueid for edit at admin page

* update venue name in the session on editVenue

* fix typo

* fixed ratings + added trigger for rating validation

* en panda i africa solved

* triggers for validating prices

* views for booking overview

* display company info on landing page

* getAllTicketTypes (service, controller implementation)

* display tickets on the landing page

---------

Co-authored-by: Norbert Tolnai <tolnainorbi16@gmail.com>

* Booking overview admin (#47)

* get MoviesWithShowings VIEW from DB

* Display MoviesWithShowings + search bar

* include component

* update views

* GET methods for showingsForMovies

* naivgation to showings of a movie

* rendering logic

* display showings for a movie

* filter by date

* get all bookings for a showing

* refactor method: getBookingsByShowingId

* remove fixed venue

* allow venue filter

* table to render bookings

* fix filters fix table

* table designs

* Image uploader (#46)

* created ImageUploader controller, service and component

* fixing github conflicts

* Create movieCRUD.php

* pushed new style

* CHANGES FROM ANDRISIS PC -MIGHT HAVE CONFLICTS

* added event listener for addMovie

* .

* continue implementing image uploader

* implementing ImageUpload R+S+C+V

* .

* label archived for archived movies

* restore movie logic throughout the layers

* finalized adding image to assets, cloudinary doesnt work yet

* cleaning code

* Image Upload news admin

* deleting unnecessary and unused snippets

* imageUploader for venue

* fixing fakiwaki

---------

Co-authored-by: 4ndris1114 <10407531@ucn.dk>

* added closing bracket

* fixed parsing json for movie edit

* upload image for venue logo

* Payment implementation with webhook (#48)

* status field added to payment

* stripe latest version included manually

* Storing the stripe keys in .env and loading it

* Temp payement file

* Test route for chekcout file

* Missing line, might not be iomportant

* Temp button for form

* Stripe payment creation

* Renaming

* Successful checkout page created

* Renaming

* temp sql script

* Temp mock data update

* Temp mockdata

* rename

* rename

* Payment entity update

* addPayment function created

* Payment entity updated

* sql script update

* Test data added for payment adding

* creating webhook file

* renaming

* webhook code added

* webhook file moved

* rename to failed

* rename to failed

* Update paymentStatus function created, dbCon moved to payment service

* Update bookingStatus function added

* dbCon brought back to repo from service

* get ids of payment function added

* PaymentStatus updated test, it is working

* Update payment based on confirmed or failed moved to webhook file

* Invoice sender function added

* Invoice sending function called

* dbSetup script renamed and altered to dev and prod

* mockdata update

* db setup script deleted to use the updated one

* unused comments removed

* Update code based on new sql script

* Update for production

* Update for production

* need for logging at least

* Small changes to production

* Error logging and code update so it works

* New email

* Delete logs

* Invoice mail was sent

* Expiration added, new event for webhook fail trigger

* typo

* New log added

* userId can be null for not authenticated users

* Webhook route

* post route for booking checkout

* Archived attribute added to movie mockData, an development db script

* Adding sanitization to data display

* session_start removed as config already starts it as it is called

* Route switched to post for charge

* Check is user exists by email

* Checkout and charge page checkout form

* Update booking user id function added

* create guest user function added

* Displaying errors, and form data

* User/guest handling for payment

* Rename to failed from cancelled

* Logic added so no rollback on form submit

* Dynamic payment data and data sanitizing

* Modal if tehre is an active booking

* Testing with the modal

* Updated rollbackBooking function and return values

* rollbackPayment function added

* In rollback route added rollbackPayment when there is an active checkout session

* Modal time expiry logic

* Unset session elements added

* Create checkoutSession in session, logic so not to create additional payments when there is an active one

* New user roles added

* Check if guest exists function and updating guest function and vakidateGuest

* Customer role updated o user

* 15 min expiry

* Check for active booking and checkout session before logout

* errorAndRedirect function, guest check and update

* Update activeBooking expiry to 30 min after payment intent

* tickets removed from booking entity

* check before rollback if the booking is pending and  only then rollback

* only update if the paymentStatus is pending

* unset session variables

* get tickets for stripe webhook expired rollback

* remove bookingExpiry from localStorage on successful payment

* try catch block for stripe webhook swicth case, for throwing exceptions for error handling

* unset moved up the function

* handle when a not logged in user is making the booking

* unset activeBooking and checkoutSesson if there is before making a new booking

* what is wrong with my github

* deleting logs

* deployment fixes

* MAGICALLY DISAPPEARING CODE MY ASS

* deployment fix

* Invoice creator implementation (#49)

* get payment by id function

* typo

* Invoice email text body providing dynamically

* Tickets retrieved through payment

* Comments

* For testing the invoice email text layout

* Removing invoice optional checkbox

* Correct parameter provided for invoice sender in stripe_webhook

* ticketService bug solved

* Testing removed

* Testing removed

* Unset localStorage timer if we logout and rollback like that

* Check if error is set

* controller updated to work

* commens deleted

* Form added

* create postal code and postal code existance check created

* address creating and existance check function added

* renaming error returning

* Address inputs added

* address handling logic added

* rollback on time expiry if activeBooking is still set

* reroute when the is an active checkout session

* back to homepage button and new text to display

* rerouting moved to checkout page

* time of expiry removed for testing

* get paymentId by bookingId function

* returning an array instead of nothing

* removing error logs from stripe webhook

* AJAX request for creating invoices through admin dashboard

* Captcha (#50)

* added phpcaptcha files

* deleting manually added files

* revert changes phptextcaptcha sucks

* Revert "revert changes phptextcaptcha sucks"

This reverts commit 796f52cc41ed565fa6edc92384d0c248e03ac614.

* added captcha to footer and checkout

* removed captcha from checkout page

* create invoice only for confirmed bookings

* admin design

* refactored

> require/include imports
> deleting unused methods

* displaying promo on landing page

> not fetching movieId! hardcoded Deadpool

* fixed merge

* onhover color navbar

* .

* .

* hover

* ?

* -_-

* displaying genres for a movie

* very important change

* fonts

* .

* changing the colors of seats to more intuitive ones

---------

Co-authored-by: 4ndris1114 <93518856+4ndris1114@users.noreply.github.com>
Co-authored-by: Norbert Tolnai <118164486+TLNRB@users.noreply.github.com>
Co-authored-by: Katarína Brezániová <10407558@ucn.dk>
Co-authored-by: Norbert Tolnai <tolnainorbi16@gmail.com>
Co-authored-by: 4ndris1114 <10407531@ucn.dk>