Booking history (#38)
* remove old test data

* BookingController->getBookingByUserId()

* BookingService->getBeookingsByUserId()

* BookingRepository->getBookingsByUserId()

* update imports

* delete Reservation.php (we have Booking.php instead)

* refactor Booking -> added tickets

* refactor Ticket -> removed booking

* TicketRepository->getTicketsByBookingId()

* TicketService->getTicketsByBookingId()

* moved ticket mapping to a separate function (removed code dupl)

* revert refactoring.... see desc:

We ran into this issue:
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 262144 bytes) in /Applications/XAMPP/xamppfiles/htdocs/dwp/src/model/services/VenueService.php on line 19

* Revert "revert refactoring.... see desc:"

This reverts commit 26d4bca32415d9616423003ca3e42cd45b7d3662.

* Refactor: Subtracting 3 years from my life expectancy, but it's worth it

* rendering booking cards

* updated python script (one booking -> one showing)

* show more button works

* show more? show less! show MORE? show LESS!